export class Constants {
    static CUSTOMER_ID = 'CUSTOMER_ID';
    static INVESTOR_NAME = 'INVESTOR_NAME';
    static FH_PAN_NO = 'FH_PAN_NO';
    static TAX_STATUS_CODE = 'TAX_STATUS_CODE';
    static TAX_STATUS_DESC = 'TAX_STATUS_DESC';
    static HOLD_N_CODE = 'HOLD_N_CODE';
    static HOLD_NATURE_DESC = 'HOLD_NATURE_DESC';
    static ACTIVATION_STATUS = 'ACTIVATION_STATUS';
    static IIN_DEACTIVATION_REASON = 'IIN_DEACTIVATION_REASON';
    static IIN_DEACTIVATION_DATE = 'IIN_DEACTIVATION_DATE';
    static CREATED_DATE = 'IIN_DEACTIVATION_DATE';
    static LAST_MODIFIED_DATE = 'LAST_MODIFIED_DATE';
}